version: "3"
services:
  api:
    container_name: nvoice-api
    build:
      context: ./apps/api/
      dockerfile: Dockerfile
    ports:
      - 4000
    env_file:
      - ./apps/api/.env
    networks:
      - nvoice_me
  web:
    container_name: nvoice-web
    build:
      context: ./apps/web/
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASEURL: https://api.nvoice.me
    ports:
      - 80
    networks:
      - nvoice_me
    env_file:
      - ./apps/web/.env
networks:
  nvoice_me:
