version: '3'
services:
  api:
    container_name: api
    build:
      context: ./apps/api/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
       - ./apps/api/.env
    networks:
      - nvoice_me
    command: ["yarn", "start"]
  web:
    container_name: web
    build:
      context: ./apps/web/
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - nvoice_me
    env_file:
      - ./apps/web/.env
networks:
  nvoice_me:
