name: Docker Image CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  REGISTRY: ghcr.io
  DOKKU_TS_HOST: 100.64.73.56
jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Get NPM version for API
      id: package-version-api
      uses: martinbeentjes/npm-get-version-action@v1.3.1
      with:
        path: apps/api
    - name: Get NPM version for Web
      id: package-version-web
      uses: martinbeentjes/npm-get-version-action@v1.3.1
      with:
        path: apps/web
    - name: Build and push Docker image for API
      uses: docker/build-push-action@v5.0.0
      with:
        context: apps/api
        push: true
        tags: ghcr.io/gokceno/nvoiceme-api:latest, ghcr.io/gokceno/nvoiceme-api:${{ steps.package-version-api.outputs.current-version}}
    - name: Build and push Docker image for Web
      uses: docker/build-push-action@v5.0.0
      with:
        context: apps/web
        push: true
        tags: ghcr.io/gokceno/nvoiceme-web:latest, ghcr.io/gokceno/nvoiceme-web:${{ steps.package-version-web.outputs.current-version}}
        build-args: |
          REACT_APP_API_BASEURL=https://api.nvoice.me
  deploy_to_dokku:
    needs: build_and_push_images
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Tailnet
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:env-ci-runner
      - name: Rebuild API
        run: ssh root@${{ env.DOKKU_TS_HOST }} "dokku ps:rebuild nvoice-api"
      - name: Rebuild Web
        run: ssh root@${{ env.DOKKU_TS_HOST }} "dokku ps:rebuild nvoice-web"
